# Generated by Django 5.2.7 on 2025-10-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=200)),
                ('codigo_estudiante', models.CharField(max_length=20)),
                ('cedula', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('carrera', models.CharField(max_length=200)),
                ('semestre', models.IntegerField()),
                ('año_academico', models.IntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
